### ISSUE TITLE
No display of another "Given" in Scenario

### ISSUE THREAD

**Issue by leilaminiailo** [qbek/CukeManager#5]
If in "Background" section a "Given" is listed, the Scenario "Given" is not displayed with CukeManager.

**Comment by qbek** [comment]
need more details eg.: screen shot and example scenario.

**Comment by leilaminiailo** [comment]
Severity: HIGH
Priority: HIGH
Reported By: Leila
Reported On: 07-04-2015
Reason: Defect
Status: New
Environment: Windows 7

Description:
"Given" section is not displayed with CukeManager.

Steps To Reproduce:
1) Open "Feature:UpdateServer - TaskManagement - flow of tasks - Initiate and finish" -> "New task for "Files upload" process" Scenario in Test Scenarios editor AND in CukeManager.

Expected result:
The Scenario starts with " Given User logs in as "pm", "pm" " in the CukeManager as in Editor is displayed

Actual result:
The Scenario starts with " And User starts "Upload new file" process on "Files" section " in the CukeManager.

![given_abscence](https://cloud.githubusercontent.com/assets/11426256/7022396/a3875040-dd2b-11e4-956d-fa0522af8f91.png)

**Comment by qbek** [comment]
Fixed.
