### ISSUE TITLE
No data table in Background section

### ISSUE THREAD

**Issue by leilaminiailo** [qbek/CukeManager#8]
Precondition: feature file with Background with data table exists, e.g.:
"Background:
    Given User opens "My Own" page
      And On "My Own" page user logs in with data:

           | email       | iwaniwanoff@domain.coml |
           | password | 1111       |    
      And On "Start" page user clicks "Sign in" button"

STEPS: 
1. Open .json file with .feature file with Background section

ACTUAL: 
    Given User opens "My Own" page
      And On "My Own" page user logs in with data:
      And On "Start" page user clicks "Sign in" button"

EXPECTED:
    Given User opens "My Own" page
      And On "My Own" page user logs in with data:
           | email       | iwaniwanoff@domain.coml |
           | password | 1111                                  |
      And On "Start" page user clicks "Sign in" button"

ENVIRONMENT:
Linux, Chrome Version 51.0.2704.84 (64-bit)

**Comment by qbek** [comment]
Fixed in version v0.1.4
