### ISSUE TITLE
Scenario Outlines parsing

### ISSUE THREAD

**Issue by leilaminiailo** [qbek/CukeManager#9]
As a User I want to have Scenario Outlines parsed by CukeManager, so that I am not to write them manually to test report and application will be more convenient

Acceptance Criteria:
* Scenario Outlines are parsed to the Scenarios according to the number of examples in Examples section
* The number of scenarios in features is counted with scenarios number in Scenario Outlines. For example:

Feature: 

Scenario1

Scenario Outline:
Examples:

|example|
|    1        |
|    2        |

Amount of scenarios: 3

**Comment by qbek** [comment]
have you checked with last version?
If you still can't view scenario outlines, please share .json file

**Comment by leilaminiailo** [comment]
I`ve checked v.0.1.4. Please see attachment.

[R3_smoke.json.zip](https://github.com/qbek/CukeManager/files/456001/R3_smoke.json.zip)

**Comment by leilaminiailo** [comment]
Issue could be closed. Or considered as feature request: to parse json file from Python version of cucumber.
In v.0.1.4 The feature was implemented and it works for cucumber from gem repo. 
Thank you!
